name: clima
description: Clima is a cutting-edge application developed as part of Angela Yu's bootcamp,
            designed to provide real-time weather information. Leveraging the power of the OpenWeather API,
            Clima fetches and displays up-to-the-minute weather data, ensuring users stay informed 
            about the current climate conditions. With a sleek and intuitive interface, 
            this project offers a seamless experience for users seeking accurate and timely weather updates..

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  http: ^1.1.0
  flutter_spinkit: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900

